/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author jeki_pc comp
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDataTeman = new javax.swing.JMenuItem();
        jMenuItemDaftarTeman = new javax.swing.JMenuItem();
        jMenuItemPinjam = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemTentangSaya = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Pilihan");

        jMenuItemDataTeman.setText("Data Teman");
        jMenuItemDataTeman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataTemanActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDataTeman);

        jMenuItemDaftarTeman.setText("Daftar Teman");
        jMenuItemDaftarTeman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDaftarTemanActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDaftarTeman);

        jMenuItemPinjam.setText("Data Pinjam");
        jMenuItemPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPinjamActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPinjam);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tentang");

        jMenuItemTentangSaya.setText("Tentang Saya");
        jMenuItemTentangSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTentangSayaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTentangSaya);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(null, "Ingin Tutup Aplikasi ini?", "PERHATIAN",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "anda akan keluar dari aplikasi ini..^^");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "anda batal keluar..^^");
        }
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void jMenuItemDaftarTemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDaftarTemanActionPerformed
        // TODO add your handling code here:
         ViewCariTeman vct = new ViewCariTeman();
        vct.setVisible(true);
    }//GEN-LAST:event_jMenuItemDaftarTemanActionPerformed

    private void jMenuItemTentangSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTentangSayaActionPerformed
        // TODO add your handling code here:
         ViewPinjam ViewPinjam1 = new ViewPinjam();
        ViewTeman ViewTeman1 = new ViewTeman();
        ViewPinjam1.setVisible(false);
        ViewTeman1.setVisible(false);
        JOptionPane.showMessageDialog(null, "Nama : jeki yakabusastro\nNPM : 15312604");
    }//GEN-LAST:event_jMenuItemTentangSayaActionPerformed

    private void jMenuItemPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPinjamActionPerformed
        // TODO add your handling code here:
         ViewPinjam ViewPinjam1 = new ViewPinjam();
        ViewTeman ViewTeman1 = new ViewTeman();
        ViewPinjam1.setVisible(true);
        ViewTeman1.setVisible(false);
    }//GEN-LAST:event_jMenuItemPinjamActionPerformed

    private void jMenuItemDataTemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataTemanActionPerformed
        // TODO add your handling code here:
         ViewTeman ViewTeman1 = new ViewTeman();
        ViewTeman1.setVisible(true);
    }//GEN-LAST:event_jMenuItemDataTemanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDaftarTeman;
    private javax.swing.JMenuItem jMenuItemDataTeman;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemPinjam;
    private javax.swing.JMenuItem jMenuItemTentangSaya;
    // End of variables declaration//GEN-END:variables
}
